// <auto-generated />
namespace DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddActivity_And_Services : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddActivity_And_Services));
        
        string IMigrationMetadata.Id
        {
            get { return "202009080559276_Add-Activity_And_Services"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
