// <auto-generated />
namespace DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateTeamMembers_TeamAbout : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateTeamMembers_TeamAbout));
        
        string IMigrationMetadata.Id
        {
            get { return "202008310838242_update-TeamMembers_TeamAbout"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
